package cnam.nsy209.selServices.association.client.view.helper;

public enum EnumMenuHorizontal {
	ASSOCIATION_DISPLAY,
	ASSOCIATION_EDIT,
	CATEGORIES_DISPLAY,
	CATEGORY_EDIT,
	FAST_MESSAGE,
	HOME,
	MEMBER_HOME,
	MEMBER_CARD,
	MEMBER_CREATE,
	MEMBER_EDIT,
	MEMBER_RESEARCH,
	MEMBER_RESEARCH_RESULT,
	MESSAGES_DISPLAY,
	TRANSACTION_EDIT,
	WEALTHSHEET_DISPLAY;

}
